controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_customers:
    path: /customers
    controller: App\Controller\CustomerController::getCustomers
    methods: GET

get_customer:
    path: /customers/{id}
    controller: App\Controller\CustomerController::getCustomer
    methods: GET
